### ISSUE TITLE
beta code to Unicode

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/lexica#2]
LSJ needs to be converted from beta code to Unicode.

**Comment by lcerrato** [comment]
@gcelano @gregorycrane just pinging this based on earlier correspondence

I would recommend comparing current version with version at time of branching and working from there.

**Comment by lcerrato** [comment]
@lcerrato spot check of converted Greek

**Comment by lcerrato** [comment]
error found in spot check
e)p' --> ἐπ'
instead of  ἐπʼ (curly quote)

**Comment by gcelano** [comment]
This is important. I will change it with Right Single Quotation Mark

**Comment by michaelhagedon** [comment]
Is there a tool you are using to do this conversion?

**Comment by lcerrato** [comment]
Hi @michaelhagedon,
I do not know what @gcelano is using for this. Other Perseus works have used a combination of the resources here:
https://github.com/PerseusDL/tei-conversion-tools/wiki/Greek-Betacode-to-Unicode-Transformations
which have their limitations.

**Comment by gcelano** [comment]
I used a few scripts that I wrote. The main one is here:

https://gist.githubusercontent.com/gcelano/98fc230470182664eb23/raw/fd333295cff4ba5e6e71299e0a16ca0c872949d4/lp:grc-convert-betacode.xq

But a few other need to be applied before it, because I parceled the task into sub-tasks. You can have a look at the scripts involved here:

http://l-processor.org/w/Ancient_Greek

I definitely need to "package" them for easier use. In the meanwhile, If I can help help with any of them, let me know.

**Comment by gcelano** [comment]
Hi @michaelhagedon,

have a look at here: https://github.com/gcelano/MorpheusGreekUnicode/blob/master/scripts/convert-betacode-into-unicode-for-Morpheus.xq

I have put together the functions for converting into Unicode. If you have BaseX, you should be able to convert your files.

**Comment by michaelhagedon** [comment]
Cool, thanks, @gcelano!

**Comment by TinaRussell** [comment]
I’m glad to see @lcerrato’s efforts over in #47, and I’m curious to know if this issue is being worked on at present. Thanks!

**Comment by lcerrato** [comment]
@TinaRussell 
Hi, no, we don't have anyone working on the conversion of the Perseus files at present.

**Comment by TinaRussell** [comment]
Okay. @gcelano, I’d like to know how to use the script you posted; I’ve tried saving the script, changing the `$d` variable definition to the location of a local copy of one of the LSJ files, and running it from the command line as `basex convert-betacode-into-unicode-for-Morpheus.xq` (in the same directory as the script, of course). It just prints the specified LSJ file raw to standard output and doesn’t change anything. What am I missing? (I’m using BaseX 9.0.1.)
Also, is the script meant to be used on the whole document, or am I supposed to identify first which tags have the “lang="greek"” and tell the script to translate just those? (I… don’t really know anything about XQuery or BaseX, I’m wingin’ it here. :disappointed_relieved:)

**Comment by gcelano** [comment]
@TinaRussell , You need to use the BaseX GUI. In any case, the script was written to make the conversion of Morpheus, which means that the script requires its XML structure to run. If you want to re-use the functions, that can be made, but the script should be changed accordingly (which also means identifying in the XML files where the Betacode is)

**Comment by TinaRussell** [comment]
@gcelano Ah, that makes sense. Thanks!
