### ISSUE TITLE
(grc.lsj.perseus-eng26.xml) typo

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/lexica#53]
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.04.0057%20%3Aentry%3D%23115926&redirect=true

According to my sources the accenuation of PSUCHOS in the following entry
should be PSU/CHOS:

**Comment by helmadik** [comment]
ψῦχος is correct for the nominative

**Comment by lcerrato** [comment]
@helmadik Thanks!
