### ISSUE TITLE
(LSJ) missing entry or incomplete?

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/lexica#56]
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.04.0057%3Aentry%3Dparale%2Fgw 
doesn't give meaning of "lie beside"

as here

http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.04.0058%3Aentry%3Dparale%2Fgw

**Comment by helmadik** [comment]
this is now lemmatized as παραλέχομαι, which can be found in LSJ.

**Comment by lcerrato** [comment]
@

**Comment by helmadik** [comment]
Not sure if this image will display but it's a 1940 LSJ. It looks ok to me, but maybe you're seeing something I'm not seeing! παραλέχομαι has its own article. 
![image](https://user-images.githubusercontent.com/7517297/108273775-a62d6700-7139-11eb-9da2-64aa97c728b3.png)

![image](https://user-images.githubusercontent.com/7517297/108274254-408daa80-713a-11eb-998d-d1cb9779b317.png)

**Comment by lcerrato** [comment]
@helmadik 
Thanks!
It was a user report and I had to put it aside when HathiTrust locked up the 1940 LSJ again.
