### ISSUE TITLE
[Lewis and Short] removing insignificant whitespace

### ISSUE THREAD

**Issue by nkprasad12** [PerseusDL/lexica#73]
Hi @lcerrato 

I'm working on a series of automation scripts to resolve some frequent tagging errors (for example, `n.` in verbs that are `v. a. and n.` sometimes being tagged as `<gen>` when in most entries it's in `<pos>`, abbreviations that are split into a different tag from their final `.`, etc...)

In order to make this task easier, I would like to send a PR doing the following:
1. Fix all instances where an `<entryFree>` is split into multiple lines. Most of the time this is actually a mistake, and the second line of the `<entryFree>` is actually its own entry in LS. There are 2 occurrences where this is legitimate, and in these cases I want to move those all in the same line. In both cases, the amount of text in the second line is very small, and wouldn't cause the first line to being prohibitively long.
2. Remove indentation before some entries. Since phase (1) makes it so that each entry is in one line, this should have no significant since it's outside the entries.
3. Remove empty lines between entries. Again, this should have no significant since it's happening outside entry boundaries.

Would this be accepted?

**Comment by lcerrato** [comment]
@nkprasad12 
Whitespace cleanup is helpful, thank you.

**Comment by nkprasad12** [comment]
Sent https://github.com/PerseusDL/lexica/pull/75 for Phase 1.

**Comment by nkprasad12** [comment]
Fixed by #75 and #76
