### ISSUE TITLE
Non-Greek/Roman characters in Lewis and Short

### ISSUE THREAD

**Issue by nkprasad12** [PerseusDL/lexica#88]
Hi @lcerrato -
I've recently finished (with the help of some friends experienced in these languages) transcribing some of the Hebrew and Syriac words in Lewis and Short. In the current version, these are just listed as empty `<foreign></foreign>`. I plan to mark Hebrew words with `lang="heb"` and Syriac with `lang="syr"`.

Since there are already unicode characters in the `lat.ls.perseus-eng2.xml` (for Greek), I was assuming that there will be no concern with adding Hebrew unicode for these missing words, but thought I should double check first.

**Comment by lcerrato** [comment]
@nkprasad12 
Please do add them!
